name: migu-sign

on:
  push:
  pull_request:
  fork:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */1 * * *

jobs:
  migu-sign:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: sign
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        ./migu.sh
